version: '3'

services:

  server:
    build:
      context: ./backend
    container_name: server
    restart: 'always'
    env_file:
      - .env
    networks:
      - camera_access_net
    ports:
      - "8000:8000"

  client:
    build:
      context: ./frontend
    container_name: client
    restart: 'always'
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - camera_access_net

networks:
  camera_access_net:
